### ISSUE TITLE
Mouse and keyboard and gestures may be selected

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#14]
We have found that testers will use a combination of keyboard, mouse, or gestures when reading. Our testing procedures need to be adjusted to allow for this combination.

**Comment by marisademeglio** [comment]
What does this scenario test that more isolated testing (e.g. just keyboard or just gestures) would miss?

**Comment by avneeshsingh** [comment]
This would defeat the purpose of having input methods. It is difficult to judge which input method is useful for which kind of disability. There may be users who depend 100% on keyboard, while there may be some who depend 70% on keyboard and 30% on mouse. 
Furthermore WCAG 2.0 makes keyboard access mandatory.
Due to all these reasons, I do not think that allowing mixing of input methods will be helpful for providing objective test results for different kind of disabilities.

**Comment by avneeshsingh** [comment]
Should we close this issue without any action?

**Comment by ways2read** [comment]
I do not know that we get any value from capturing this information.
